import json
from pathlib import Path


def sub(path, old, new, n=1):
    p=Path(path); s=p.read_text()
    if s.count(old) < n: raise SystemExit(f'{path}: missing {old[:80]!r}')
    p.write_text(s.replace(old,new,n))

# Source ownership: extend existing local-storage extractor instead of adding another one.
s='toolchain/codex_wire_audit/extractors/local_storage_specs.py'
sub(s,'SCHEMA_VERSION = "1.0.0"','SCHEMA_VERSION = "2.0.0"')
sub(s,'    "history_materialization": "source_spec.extra.local_storage_history_materialization",\n',
'''    "history_materialization": "source_spec.extra.local_storage_history_materialization",\n    "local_store": "source_spec.extra.local_storage_local_store",\n    "live_writer": "source_spec.extra.local_storage_live_writer",\n    "rollout_resolver": "source_spec.extra.local_storage_rollout_resolver",\n    "model_context": "source_spec.extra.local_storage_model_context",\n    "history_read": "source_spec.extra.local_storage_history_read",\n''')
sub(s,'    "shell_snapshot": (', '''    "local_store": ("LocalThreadStore", "live_recorders", "ensure_live_recorder_absent"),\n    "live_writer": ("SQLite is a rebuildable view.", "durable_write", "materialize_to_sqlite"),\n    "rollout_resolver": ("SQLite's selected rollout path", "resolve_current", "LookupScope"),\n    "model_context": ("load_latest_model_context", "ReverseJsonlScanner", "resolve_rollout_lineage"),\n    "history_read": ("list_turns", "list_items", "thread_history_db"),\n    "shell_snapshot": (''')

r='toolchain/codex_wire_audit/source_registry.py'
anchor='        ("source_spec.extra.local_storage_history_materialization", "local_storage_history_materialization", "codex-rs/thread-store/src/local/thread_history_materialization.rs", ("materialize_to_sqlite", "next_byte_offset", "next_ordinal")),\n'
sub(r,anchor,anchor+'''        ("source_spec.extra.local_storage_local_store", "local_storage_local_store", "codex-rs/thread-store/src/local/mod.rs", ("LocalThreadStore", "live_recorders", "ensure_live_recorder_absent")),\n        ("source_spec.extra.local_storage_live_writer", "local_storage_live_writer", "codex-rs/thread-store/src/local/live_writer.rs", ("SQLite is a rebuildable view.", "durable_write", "materialize_to_sqlite")),\n        ("source_spec.extra.local_storage_rollout_resolver", "local_storage_rollout_resolver", "codex-rs/thread-store/src/local/thread_rollout_resolver.rs", ("resolve_current", "LookupScope", "rollout_path")),\n        ("source_spec.extra.local_storage_model_context", "local_storage_model_context", "codex-rs/thread-store/src/local/model_context.rs", ("load_latest_model_context", "ReverseJsonlScanner", "resolve_rollout_lineage")),\n        ("source_spec.extra.local_storage_history_read", "local_storage_history_read", "codex-rs/thread-store/src/local/thread_history/read.rs", ("list_turns", "list_items", "thread_history_db")),\n''')

l='toolchain/codex_wire_audit/extractors/local_storage_layout.py'
sub(l,'\ndef build_databases(','''\ndef build_read_paths() -> dict[str, Any]:\n    return {\n        "cold_resume_model_context": {"selected_rollout_authority": "state_5.sqlite rollout_path for paginated threads after live-writer resolution", "source": "selected immutable rollout JSONL lineage", "reader": "load_latest_model_context", "scan": "reverse JSONL scan across resolved lineage", "uses_thread_history_projection": False},\n        "paginated_query_history": {"source": "$SQLITE_HOME/thread_history_1.sqlite", "apis": ["list_turns", "list_items"], "persists_across_restart": True, "full_replay_on_restart": False},\n    }\n\ndef build_projection_semantics() -> dict[str, Any]:\n    return {\n        "canonical_source": "rollout JSONL",\n        "projection": "$SQLITE_HOME/thread_history_1.sqlite",\n        "role": "persistent rebuildable acceleration view",\n        "write_order": ["durable JSONL write", "incremental SQLite projection"],\n        "checkpoint": ["next_rollout_byte_offset", "next_rollout_ordinal"],\n        "update_mode": "project durable JSONL suffix after persisted checkpoint",\n        "projected_prefix_must_be_immutable": True,\n        "may_lag_after_failure": True,\n        "may_get_ahead": False,\n        "rebuild_on_restart": False,\n        "external_rewrite": {"supported": False, "shrink_error": "durable rollout shrank before projection", "automatic_reset": False},\n    }\n\ndef build_databases(''')
sub(l,'            "rollout_jsonl": "canonical durable replay history",\n            "state_database": "mutable metadata index and current-rollout pointer",\n            "thread_history_database": "derived paginated projection",',
'''            "rollout_jsonl": "canonical durable append-only replay history",\n            "state_database": "operational metadata plus authoritative current-rollout pointer for paginated threads",\n            "thread_history_database": "persistent rebuildable acceleration projection derived from rollout JSONL",''')

lc='toolchain/codex_wire_audit/extractors/local_storage_lifecycle.py'
sub(lc,'            "precondition": "paginated thread with state database",\n', '''            "precondition": "paginated thread with state database and no live recorder",\n            "cutoff_parameter": "before_turn_id",\n            "cutoff_granularity": "turn boundary",\n            "supports_intra_turn_item_cutoff": False,\n''')
sub(lc,'        {\n            "id": "local_storage.sidecars_follow_thread_identity",', '''        {\n            "id": "local_storage.thread_history_sqlite_is_acceleration",\n            "statement": "thread_history_1.sqlite is a persistent acceleration projection; rollout JSONL remains canonical durable history",\n        },\n        {\n            "id": "local_storage.external_rewrite_does_not_auto_rebuild_projection",\n            "statement": "the incremental projector assumes an immutable projected prefix and does not automatically rebuild after external JSONL rewrite",\n        },\n        {\n            "id": "local_storage.sidecars_follow_thread_identity",''')

x='toolchain/codex_wire_audit/extractors/local_storage.py'
sub(x,'    build_scope, build_roots, build_identity_domains, build_rollouts, build_databases,\n', '    build_scope, build_roots, build_identity_domains, build_rollouts, build_read_paths, build_projection_semantics, build_databases,\n')
sub(x,'                "https://schemas.codex-wire-audit.invalid/v19/"\n                "local-storage-semantics-v1.schema.json"', '                "https://schemas.codex-system-contract.invalid/storage/"\n                "local-storage-semantics-v2.schema.json"')
sub(x,'            "databases": build_databases(', '            "read_paths": build_read_paths(),\n            "projection_semantics": build_projection_semantics(),\n            "databases": build_databases(')
sub(x,'                    "database_pointer": [', '''                    "read_paths": ["rollout_resolver", "model_context", "history_read"],\n                    "projection_semantics": ["live_writer", "history_materialization", "history_read"],\n                    "database_pointer": [''')

# Add v2 schema by extending v1; keep v1 packaged for existing consumers.
p=Path('toolchain/codex_wire_audit/proof_schema_templates/local-storage-semantics-v1.schema.json')
schema=json.loads(p.read_text())
schema['$id']='https://schemas.codex-system-contract.invalid/storage/local-storage-semantics-v2.schema.json'
schema['title']='Codex local storage, replay, and projection semantics'
schema['properties']['$schema']={'const':schema['$id']}
for k in ('read_paths','projection_semantics'):
    if k not in schema['required']: schema['required'].append(k)
schema['properties']['read_paths']={"type":"object","additionalProperties":False,"required":["cold_resume_model_context","paginated_query_history"],"properties":{
 "cold_resume_model_context":{"type":"object","additionalProperties":False,"required":["selected_rollout_authority","source","reader","scan","uses_thread_history_projection"],"properties":{"selected_rollout_authority":{"type":"string"},"source":{"const":"selected immutable rollout JSONL lineage"},"reader":{"const":"load_latest_model_context"},"scan":{"type":"string"},"uses_thread_history_projection":{"const":False}}},
 "paginated_query_history":{"type":"object","additionalProperties":False,"required":["source","apis","persists_across_restart","full_replay_on_restart"],"properties":{"source":{"const":"$SQLITE_HOME/thread_history_1.sqlite"},"apis":{"const":["list_turns","list_items"]},"persists_across_restart":{"const":True},"full_replay_on_restart":{"const":False}}}}}
schema['properties']['projection_semantics']={"type":"object","additionalProperties":False,"required":["canonical_source","projection","role","write_order","checkpoint","update_mode","projected_prefix_must_be_immutable","may_lag_after_failure","may_get_ahead","rebuild_on_restart","external_rewrite"],"properties":{
 "canonical_source":{"const":"rollout JSONL"},"projection":{"const":"$SQLITE_HOME/thread_history_1.sqlite"},"role":{"const":"persistent rebuildable acceleration view"},"write_order":{"const":["durable JSONL write","incremental SQLite projection"]},"checkpoint":{"const":["next_rollout_byte_offset","next_rollout_ordinal"]},"update_mode":{"type":"string"},"projected_prefix_must_be_immutable":{"const":True},"may_lag_after_failure":{"const":True},"may_get_ahead":{"const":False},"rebuild_on_restart":{"const":False},"external_rewrite":{"type":"object","additionalProperties":False,"required":["supported","shrink_error","automatic_reset"],"properties":{"supported":{"const":False},"shrink_error":{"const":"durable rollout shrank before projection"},"automatic_reset":{"const":False}}}}}
Path('toolchain/codex_wire_audit/proof_schema_templates/local-storage-semantics-v2.schema.json').write_text(json.dumps(schema,indent=2)+'\n')

# Tests/closure.
t='toolchain/tests/test_local_storage_v19.py'; tp=Path(t); ts=tp.read_text();
if ts.count('local-storage-semantics-v1.schema.json') != 2: raise SystemExit('test schema reference count drift')
ts=ts.replace('local-storage-semantics-v1.schema.json','local-storage-semantics-v2.schema.json')
fixture='''\nSOURCE_TEXTS.update({\n    "local_store": "pub struct LocalThreadStore { live_recorders: Vec<()> }\\nfn ensure_live_recorder_absent() {}\\n",\n    "live_writer": "// SQLite is a rebuildable view.\\nasync fn durable_write() {}\\nmaterialize_to_sqlite();\\n",\n    "rollout_resolver": "// SQLite's selected rollout path is authoritative.\\nfn resolve_current() {}\\nenum LookupScope { ExcludeArchived, IncludeArchived }\\n",\n    "model_context": "fn load_latest_model_context() {}\\nstruct ReverseJsonlScanner;\\nresolve_rollout_lineage();\\n",\n    "history_read": "fn list_turns() {}\\nfn list_items() {}\\nfn thread_history_db() {}\\n",\n})\n'''
ts=ts.replace('\ndef _snapshot(',fixture+'\ndef _snapshot(',1)
ts += '''\n\ndef test_local_storage_restart_projection_semantics_are_explicit() -> None:\n    result, _ = _extract()\n    assert result.data["read_paths"]["paginated_query_history"]["full_replay_on_restart"] is False\n    p = result.data["projection_semantics"]\n    assert p["role"] == "persistent rebuildable acceleration view"\n    assert p["write_order"] == ["durable JSONL write", "incremental SQLite projection"]\n    assert p["checkpoint"] == ["next_rollout_byte_offset", "next_rollout_ordinal"]\n    assert p["external_rewrite"] == {"supported": False, "shrink_error": "durable rollout shrank before projection", "automatic_reset": False}\n    r = result.data["transitions"]["revert"]\n    assert r["cutoff_parameter"] == "before_turn_id"\n    assert r["cutoff_granularity"] == "turn boundary"\n    assert r["supports_intra_turn_item_cutoff"] is False\n'''
tp.write_text(ts)
rel=Path('toolchain/codex_wire_audit/release_spec.v1.json'); rs=rel.read_text();
if rs.count('proof_schema_templates/local-storage-semantics-v1.schema.json') != 1: raise SystemExit('release resource drift')
rel.write_text(rs.replace('proof_schema_templates/local-storage-semantics-v1.schema.json','proof_schema_templates/local-storage-semantics-v2.schema.json',1))

d=Path('LOCAL_STORAGE_AND_ROLLOUT_LAYOUT.md'); ds=d.read_text(); marker='The authoritative `session_id` is therefore read from rollout session metadata, not inferred from SQLite.\n'
if marker not in ds: raise SystemExit('doc anchor drift')
ds=ds.replace(marker,marker+'''\n### Replay versus projection authority\n\n`thread_history_1.sqlite` is a persistent acceleration projection, not canonical history. Codex writes durable rollout JSONL first, then projects only the new suffix after its stored byte/ordinal checkpoint. The projection persists across process restart and is not rebuilt from the full JSONL on every startup.\n\nCold paginated model-context resume instead resolves the selected rollout and reverse-scans its immutable JSONL lineage. Paginated `list_turns` / `list_items` queries read the persisted SQLite projection. For paginated threads, `state_5.sqlite.threads.rollout_path` selects the current immutable rollout revision.\n\nThe projector assumes already-projected JSONL bytes are immutable. External truncation behind the checkpoint fails with `durable rollout shrank before projection`; normal restart does not automatically reset/rebuild the projection.\n''',1)
d.write_text(ds)
